packages:
  - playground

overrides:
  "@nuxt/kit": "4.4.6"
  "@nuxtjs/turnstile": "link:."

shamefullyHoist: true

strictPeerDependencies: false

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
